export const ProductsData = [
  {
    login: "iTemix",
    id: 86549498,
    node_id: "MDQ6VXNlcjg2NTQ5NDk4",
    avatar_url: "https://avatars.githubusercontent.com/u/86549498?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/iTemix",
    html_url: "https://github.com/iTemix",
    followers_url: "https://api.github.com/users/iTemix/followers",
    following_url: "https://api.github.com/users/iTemix/following{/other_user}",
    gists_url: "https://api.github.com/users/iTemix/gists{/gist_id}",
    starred_url: "https://api.github.com/users/iTemix/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/iTemix/subscriptions",
    organizations_url: "https://api.github.com/users/iTemix/orgs",
    repos_url: "https://api.github.com/users/iTemix/repos",
    events_url: "https://api.github.com/users/iTemix/events{/privacy}",
    received_events_url: "https://api.github.com/users/iTemix/received_events",
    type: "User",
    site_admin: false,
    name: "Temiloluwa Adegoke",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: "highlove03",
    public_repos: 19,
    public_gists: 0,
    followers: 3,
    following: 6,
    created_at: "2021-06-27T07:49:28Z",
    updated_at: "2022-10-09T15:18:21Z",
  },
];
